### ISSUE TITLE
Add support for upcoming proto3 field presence

### ISSUE THREAD

**Issue by perezd** [elixir-protobuf/protobuf#104]
the `optional` keyword is coming back in proto3 (as of v 3.12), and this will enable the ability to declare explicit presence tracking which should introduce the generation of `hasXXX` style methods on fields. 

* Context: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
* Implementation notes: https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md

**Comment by whatyouhide** [comment]
`optional` has been released in [version 3.15 of Protobuf](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0). We can now probably support this.

**Comment by junaid1460** [comment]
No update yet, blocks me, should I take forward that PR #265 ?

**Comment by whatyouhide** [comment]
@junaid1460 we're working on #265.

**Comment by whatyouhide** [comment]
Closed via #265.
