### ISSUE TITLE
Imports not working as expected

### ISSUE THREAD

**Issue by peburrows** [elixir-protobuf/protobuf#106]
I'm trying to generate code from some proto files that use `import` extensively ([this datastore definition](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto), for instance), and while `protoc` runs successfully, the generated code seems to be missing module and struct definitions for the messages defined in the imported proto files.

I threw together a quick repo that demonstrates what I'm seeing, [here](https://github.com/peburrows/grpc-imports-failure-example) (quick instructions to reproduce are in the readme). You'll notice via the failing test that, though the `Key` proto message is defined in the imported `google/datastore/v1/entity.proto` file, it doesn't end up in the resulting generated code.

Am I just doing something wrong, or is this behavior expected / not yet implemented?

**Comment by aquarhead** [comment]
I believe this lib's `protoc` integration only generates for a single file (in fact, I _think_ all protoc output behaves this way) so you'll need to iterate over all the files to generate them.

Disclaimer: I haven't looked for updates here for quite some time, but that's how we were using this.

**Comment by whatyouhide** [comment]
As far as I can tell, @aquarhead's comment solves this issue. @peburrows if you are still having problems, please comment down here 👇 and we'll take a look 🙃 Thanks everyone! ❤️
