### ISSUE TITLE
Errors with Google conformance tests

### ISSUE THREAD

**Issue by ahamez** [elixir-protobuf/protobuf#107]
Hi,

I'm working on another protobuf library, [protox](https://github.com/ahamez/protox). My main objective being to be 100% compliant with the Google conformance test, I wondered how other libraries performed in this regard. I thought you might be interested in the results I found.

To sum up, out of 1302 tests, 123 are failing. It covers only binary serialization: I did not test JSON encoding/decoding as protox does not support JSON.

You can find the detailed results in a gist [here](https://gist.github.com/ahamez/58a7412a48949fb1f91341b78c9c4f11). The first file, `conformance.txt` is the output of the Google executable that performs the conformance test. You'll find it's quite cumbersome to read (for instance, they use an octal notation and when the value corresponds to a printable character, it's not displayed with the octal notation).
This is why there's another file, `report.txt` that is generated by the script that drives the conformance executable. It provides a more legible view of all the inputs received.

The code of the script that runs the test is available [here](https://github.com/ahamez/protox/blob/benchmark_protobuf/conformance/protox/conformance/escript.ex), and the files generated from the `.proto` (with the command `protoc --elixir_out=. ...`) used for the test are [here](https://github.com/ahamez/protox/blob/benchmark_protobuf/conformance/protox/conformance/test_messages_proto2.pb.ex) and [here](https://github.com/ahamez/protox/blob/benchmark_protobuf/conformance/protox/conformance/test_messages_proto3.pb.ex).

You can reproduce the test yourself with the following steps (requires a C++ compiler):
- `git clone https://github.com/ahamez/protox.git`
- `wget https://github.com/google/protobuf/archive/v3.12.1.tar.gz`
- `tar xf v3.12.1.tar.gz && cd protobuf-3.12.1 && ./autogen.sh && ./configure && make -j && cd conformance && make -j && cd ../..` (compile Google conformance checker, it can take a while)
- `git checkout benchmark_protobuf`
- `mix deps.get`
- `mix protox.conformance --runner=./protobuf-3.12.1/conformance/conformance-test-runner` (don't mind the `protox` in the command, it's just the mix task that drives everything).

Of course, I might have missed something when using your library, so feel free to correct me if I'm wrong!

**Comment by perezd** [comment]
I think this is a good idea, so I've begun adding preliminary support for conformance testing in this project as of #114. I'll expand support for other test variations once this is merged.

**Comment by ahamez** [comment]
Nice! If you need help in fixing those tests, don't hesitate to contact me, it was pretty tedious to figure out how to have an 100% compliant library as the Google documentation hides some details. For instance, when negative, a varint32 has to be encoded [like a varint64](https://github.com/ahamez/protox/commit/4c5e8e3b06793b2a2e47b203dd318a8d43b04e60) 🤔.

**Comment by whatyouhide** [comment]
@britto didn't we fix these conformance tests at this point, or am I remembering wrong? 🤔

**Comment by britto** [comment]
@whatyouhide we fixed some of them, but it would be great if we could fix the remaining ones and keep up with upstream conformance tests. I've just given #114 a test run from protobuf master (3.19.x) and it reported:

```
CONFORMANCE SUITE FAILED: 1153 successes, 715 skipped, 121 expected failures, 28 unexpected failures.
```

**Comment by whatyouhide** [comment]
Closing this now that we have conformance tests set up. Will work through them and open more specific issues as we go. Thanks @perezd! 💟
