### ISSUE TITLE
Remove @moduledoc false from generated modules

### ISSUE THREAD

**Issue by jeffutter** [elixir-protobuf/protobuf#108]
I realize this was added on purpose (https://github.com/tony612/protobuf-elixir/pull/17) I'm wondering if we could remove the `@moduledoc false` or make it optional?

We generate documentation for RPC clients that use the generated proto modules. It would be really handy if the docs included the protobuf modules, if only for the type definition.

I can open a PR for this if it would be a welcome addition.

**Comment by whatyouhide** [comment]
What kind of documentation would you put in those files @jeffutter?

**Comment by zetaron** [comment]
Hey @jeffutter I've created the PR #123 which includes annotated comments from proto files in the generated Elixir Code.

Maybe you can take a look and see if that would be an improvement to your current situation.

**Comment by jeffutter** [comment]
@zetaron Taking a quick look at the PR and the examples - looks good. I'll see If I can get this branch installed and run it on our codebase tomorrow.

**Comment by skbolton** [comment]
@jeffutter @zetaron anything new around this? I am also interested in more docs and specs being pulled over when generating modules.

**Comment by whatyouhide** [comment]
Hey @jeffutter, closing this in favor of the PR. Thanks!
