### ISSUE TITLE
Type wrappers (newtypes) encoding optimisation

### ISSUE THREAD

**Issue by tim2CF** [elixir-protobuf/protobuf#131]
Protobuf is binary format, and in general, protobuf schema is segregated from runtime data. This means information about types and fields don't exist in encoded messages (opposite to JSON). We completely rely on decoder and assume it knows schema and can figure out how to decode given bytes. Let's say we have 2 messages

```protobuf
message Date {
  uint32 iso_days = 1;
}

message DateWrapper {
  Date date = 1;
}
```

From my point of view, encoded representation of them should be completely the same (uint32) because they both have only one field, and there are no alternative ways how to decode the value - meaningful part is always just uint32, all information about types is coming from the schema which is not a part of encoded message. But at the same time, for some reason encoded representation contains some extra bytes which seems for me completely redundant (because of reasons I described before like segregated schema). Example

```elixir
iex> d = Date
iex> dw = DateWrapper
iex> d.new(iso_days: 1) |> d.encode
<<8, 1>>
iex> dw.new(date: d.new(iso_days: 1)) |> dw.encode
<<10, 2, 8, 1>>
```

Can we optimise encoding of these type wrappers aka newtypes?

**Comment by britto** [comment]
Hey, @tim2CF. That's a clever idea and –to some extent– libraries do optimize the representation of Google's [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) officially, but it is limited to the unmarshalled data structures, we can't do much when it comes to the _wire format_ though. It must be strictly compliant to the spec, otherwise we can't guarantee other clients will decode our data correctly.

The Protobuf JSON mapping on the other hand, has some [definitions](https://developers.google.com/protocol-buffers/docs/proto3#json) on how to encode/decode these well-known types and it optimizes _wrapper types_, for example, by using the raw values and allowing `null` at their keys.

**Comment by tim2CF** [comment]
Hi @britto ! 
So standard itself requires these additional bytes? That's sad, because these newtypes (wrappers) are extremely good for well-typed API design, because plain int/string/byte types are blind, and we have to rely on field names or comments to help people to guess what does particular value mean. And even if people will guess, for computers two values `uint64 seconds` and `uint64 money_amount` will be completely undistinguishable, it creates huge possibilities for the bugs.

In Haskell we are using definition called newtype to solve this blindness issue 
https://github.com/coingaming/lnd-client/blob/d8be2338ffb8d9a2a14af81b81ed0b942ea207b7/src/LndClient/Data/Newtype.hs#L66-L67
https://github.com/coingaming/lnd-client/blob/d8be2338ffb8d9a2a14af81b81ed0b942ea207b7/src/LndClient/Data/Newtype.hs#L75-L76

In runtime they still will be uint64 values, but for compiler they are different types. It will not let you to add Seconds to MoneyAmount, or use MoneyAmount value where Seconds are needed. One of the greatest benefits there - literally zero runtime memory and CPU overhead. I would like to promote similar architectural idea for protobuf documents, but as you see in case of protobuf there is non-zero runtime overhead, so I can't promote it because runtime cost is too high. Do you have any ideas how we can have newtypes in protobuf, but without runtime overhead?

**Comment by whatyouhide** [comment]
Hey @tim2CF, we'll take a look at this but I’m closing this issue for now since it's not pressing nor a bug. We'll pick it up again when we'll have a chance to do another round of performance improvements on the library. Thank you so much for all the discussion and context 😌 💟
