### ISSUE TITLE
Google.Protobuf.Any pack unpack

### ISSUE THREAD

**Issue by sleipnir** [elixir-protobuf/protobuf#134]
Hello, I admire this library and I intend to use it in a production system but in this project we depend a lot on the Any type, I would like to know if there is support for Any type? If yes, is there any usage example? In other languages like Java or Python we have the pack and unpack methods that enable us to decode and encode any type to the Protobuf Any type.

**Comment by wingyplus** [comment]
Any are also support in https://github.com/elixir-protobuf/google-protos/blob/master/lib/google_protos/any.pb.ex#L1

**Comment by isaacsanders** [comment]
I feel like converting the URL into a Module then decoding from the module definition might be a way to do it, but I have no idea if that is possible.

**Comment by spokc** [comment]
@sleipnir Can you please post the full working example ?

**Comment by sleipnir** [comment]
> @sleipnir Can you please post the full working example ?

https://github.com/eigr/massa/blob/db4f2edb2dd0ed306a0f27dbd91aece9c5772546/massa_proxy/apps/massa_proxy/lib/massa_proxy/util.ex#L3

https://github.com/eigr/massa/blob/db4f2edb2dd0ed306a0f27dbd91aece9c5772546/massa_proxy/apps/massa_proxy/lib/massa_proxy/protocol/action/unary_handler.ex#L28

Does it help you?

**Comment by spokc** [comment]
@sleipnir Thanks. I have tried the same with your source as the reference.

But, according to the spec, the type key is to be given as `@type`, instead the library seems to be using `type_url`. Couldn't integrate the same with compliant specs

What can we do here ?

Regards

**Comment by sleipnir** [comment]
@spokc I think you are referring to the protobuf's JSON encoding and not the protobuf encoding itself. My implementation was tested against Python and Java clients without problems with Probuf without Json encoding, only native protobuf client server.

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/any.proto#L91

See that I don't change the type defined by the specification, I just add the value for type_url as due. I believe it is a problem with the Json encoding of the protobuf library and not with the creation of the Any type by the client code.

What I saw about @type in the spec refers to JSON encoding only and not the type url itself:

type_url spec:
https://github.com/protocolbuffers/protobuf/blob/ee04809540c098718121e092107fbc0abc231725/src/google/protobuf/any.proto#L91

Json spec:
https://github.com/protocolbuffers/protobuf/blob/ee04809540c098718121e092107fbc0abc231725/src/google/protobuf/any.proto#L101

I think we are talking about different things. Can you explain your use case?

**Comment by spokc** [comment]
@sleipnir Sorry wasn't very clear before. Yes I was indeed talking about JSON encoding. We're exposing both grpc & HTTP/JSON APIs and the most common language is JSON

https://github.com/elixir-protobuf/google-protos/blob/master/lib/google_protos/any.pb.ex#L11 -> Adding `, json_name: "@type"` to this line could help

Regards

**Comment by spokc** [comment]
@sleipnir That wouldn't help, as i thought that JSON mapping is implemented completely. Seems like we already have one issue #86 already. Whatever we have doesn't support proto's `Any` type yet

**Comment by sleipnir** [comment]
@spokc Was #86 not solved by #105 and #109 ?

**Comment by spokc** [comment]
@sleipnir Unfortunately, no. `Any` isn't supported yet. Ref: https://github.com/elixir-protobuf/protobuf/blob/master/lib/protobuf/json.ex#L27

**Comment by whatyouhide** [comment]
Closing this in favor of the JSON-focused issue, #208. Thanks everyone! 💟
