### ISSUE TITLE
last _ (underscore) is truncated in message names.

### ISSUE THREAD

**Issue by vans163** [elixir-protobuf/protobuf#137]
a field defined in the .proto as message HAS_UNDERSCORES_5 becomes `defmodule HAS_UNDERSCORES5` or HAS_HAS_U_5_5 becomes HAS_HAS_U_55.

Seems to be an issue with
```
  def normalize_type_name(name) do
    name
    |> String.split(".")
    |> Enum.map(&Macro.camelize(&1))
    |> Enum.join(".")
  end
```
Macro.camelize in util.ex

**Comment by whatyouhide** [comment]
I discussed this with the Elixir core team. `Macro.camelize/1` behaves consistently. I think in this case this library is doing the right thing. You can customize the module name and I think that's what you should do if you want a name different than the one that gets generated. Thanks for the report though! 💟
