### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by bnadlerjr** [elixir-protobuf/protobuf#143]
Hi! The main branch has JSON encoding/decoding support I'd like to use. Curious if there's a release planned since I don't want to have to add a dependency on the main branch.

**Comment by maennchen** [comment]
@bnadlerjr I would really appreciate a release.

The protos of this library use `extend`. If I'd use the dependency via git, I could no longer publish it to hex.

https://github.com/jshmrtn/zitadel_api/pull/3  
https://github.com/jshmrtn/zitadel_api/pull/3/checks?check_run_id=2294694580

**Comment by whatyouhide** [comment]
Hey @bnadlerjr, we're working on a release. It will take a few weeks. For now, you'll have to work with using the library as a Git dependency. Thanks!
