### ISSUE TITLE
Custom option for generating multiple *.pb.ex files

### ISSUE THREAD

**Issue by rmertzpfpt** [elixir-protobuf/protobuf#153]
Would be nice to have a custom option to generate separate `.pb.ex` files per message in a single `.proto` files when using `protoc-gen-elixir`. Similar to the option available in the java protoc plugin: `option java_multiple_files = true;`

**Comment by whatyouhide** [comment]
@rmertzpfpt heyo, thanks for the proposal! Can you expand on what is the use case you'd be using this for?

**Comment by britto** [comment]
@whatyouhide we have an example of that in our integration tests. Multiple types defined in a single file, `test/protobuf/protoc/proto/test.proto`, end up generating multiple modules in a single `.pb.ex` file, `test/protobuf/protoc/proto_gen/test.pb.ex`.

I believe the ask here is to provide an option to generate one `.pb.ex` file per generated module.

**Comment by rmertzpfpt** [comment]
re: @whatyouhide 

@britto that is correct. The use case here is mainly around convention. It would be easier to browse generated modules in separate `.pb.ex` files as well as managing/monitoring changes resulting from `.proto` changes in version control.

**Comment by whatyouhide** [comment]
I think I would be ok with generating one file per generated module (behind an option). We would do

```bash
protoc --elixir_out=one_file_per_module=true:...
```

One last question @britto and @rmertzpfpt: we should generate the proper directory structure (that is, `Foo.MyEnum` goes into `foo/my_enum.pb.ex`) or just underscore everything (`Foo.MyEnum` goes in `foo_my_enum.pb.ex`)?

**Comment by rmertzpfpt** [comment]
@whatyouhide , I think proper directory structure makes the most sense - it is what was in mind when I originally made the feature request.
