### ISSUE TITLE
Add support for optional keyword (it is in proto3 since release 3.1)

### ISSUE THREAD

**Issue by jonathantawfik** [elixir-protobuf/protobuf#156]
When trying to include optional fields in a proto3 message I get this error :
proto/pns.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-elixir hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--elixir_out:

**Comment by whatyouhide** [comment]
Closing since this is a duplicate of #104. Thanks @jonathantawfik! 💟
