### ISSUE TITLE
oneof fields incorrectly skipped when value matches the default

### ISSUE THREAD

**Issue by mikebveil** [elixir-protobuf/protobuf#239]
There is a [rule](https://github.com/elixir-protobuf/protobuf/blob/6b8f40f206375c36666f2cc9a570a061f9f0d89a/lib/protobuf/encoder.ex#L78) in `encoder.ex`to skip encoding of a field value if it matches the field's default value. This is incorrect in the case of `oneof` fields, since the explicit value lets us determine which case was set. Note the the [language guide](https://developers.google.com/protocol-buffers/docs/proto#oneof) also indicates that the field should be set in this case:
> If you set a oneof field to the default value (such as setting an int32 oneof field to 0), the "case" of that oneof field will be set, and the value will be serialized on the wire.

The current behavior is that the field is skipped, and then becomes blank on decoding. I have a simple fix that I've provided as a PR.

**Comment by mikebveil** [comment]
@whatyouhide: Is there an ETA at this point for a release that includes this fix? We are upgrading from 0.6.3 for performance reasons, and this was blocking us. Our plan is to use the next release from you if it's coming in the next few weeks, rather than using our own fork.

**Comment by whatyouhide** [comment]
@mikebveil I'll try to get a new version out this week!

**Comment by mikebveil** [comment]
One last ping on this one, @whatyouhide.
