### ISSUE TITLE
How to convert from Elixir DateTime to Google.Protobuf.Timestamp

### ISSUE THREAD

**Issue by alberthives** [elixir-protobuf/protobuf#241]
Hi,

I have a fairly simple problem I am trying to solve but can't find any documentation.

I have defined a field, time, in a proto with the following type: google.protobuf.Timestamp

The Elixir code that is generated for the field is as follows: <my_namespace>.Google.Protobuf.Timestamp

Now, I am attempting to map an Elixir DateTime type to Google.Protobuf.Timestamp and was wondering how I would do that.

Thanks.

**Comment by whatyouhide** [comment]
Heyo, `Google.Protobuf.Timestamp` is made of a seconds field and a nanoseconds field. You can convert an Elixir `DateTime` to those like this:

```elixir
seconds = datetime |> DateTime.truncate(:second) |> DateTime.to_unix(:second)
nanos = DateTime.to_unix(datetime, :nanosecond) - seconds
```

If you want to do this automatically, I'd recommend looking into [`Protobuf.TransformModule`](https://hexdocs.pm/protobuf/Protobuf.TransformModule.html).

Thanks! 💟

**Comment by alberthives** [comment]
Thanks @whatyouhide.
