### ISSUE TITLE
protoc: error when referencing lower case type as field type

### ISSUE THREAD

**Issue by jeanparpaillon** [elixir-protobuf/protobuf#250]
Let a message type:

```protobuf
message my_basic_type {
  ...
}
```

Let `my_basic_type` being referenced later:

```protobuf
message my_type {
   my_basic_type my_var=1
}
```

The generated code is:

```elixir
field :my_var, 1, type: my_basic_type
```

That should be:

```elixir
field :my_var, 1, type: MyBasicType
```

`MyBasicType` module is generated correctly

**Comment by whatyouhide** [comment]
Oh, nice catch @jeanparpaillon!

I'm closing this in favor of #251, thank you so much for getting a PR ready already 💟
