### ISSUE TITLE
Plugin version

### ISSUE THREAD

**Issue by jeanparpaillon** [elixir-protobuf/protobuf#256]
Plugin version should be more precise

When building plugin from sources, it reports a fixed version (from `mix.exs`). Sthg like `git describe` should be used to avoid confusion.
As of today, library from HEAD is not compatible with code generated with plugin 0.9.0 (released)

**Comment by whatyouhide** [comment]
I believe the solution to this is to do what many other tools do, such as Elixir itself: use `<version>-dev` as the version when developing and only remove the `-dev` suffix right when releasing. This would ensure that no locally-built plugin has a version that has been published to Hex. What do you think?

**Comment by jeanparpaillon** [comment]
My concern is to differentiate released version from version built from HEAD (especially for plugin).
So, this solution is fine for me.
