### ISSUE TITLE
Use atom keys for maps

### ISSUE THREAD

**Issue by yordis** [elixir-protobuf/protobuf#276]
Hey there, I have the following proto:

```proto
message PostingInstruction {
  map<string, string> instruction_details = 17;
}
```

I wondering if when I decode `instruction_details` the key of the map could be an atom instead of string.

**Comment by whatyouhide** [comment]
@yordis the library provides a functionality under [`Protobuf.TransformModule`](https://hexdocs.pm/protobuf/0.10.0/Protobuf.TransformModule.html) that lets you pipe decoded/encoded data through a module of your choice before decoding/encoding.

You can use that to achieve what you want. IIRC, maps are internally defined as a repeated map entry message or something like that. So, you might achieve what you want with:

```elixir
defmodule AtomKeys do
  @behaviour Protobuf.TransformModule

  @impl true
  def decode(map, ...) do
    # Logic to convert string keys to atoms here
  end
end
```

You'll have to tinker a bit with this to get it to work, I can't dig deeper than this right now 😄 Let me know how it goes 🙃 

As for adding this to the library, we won't add the functionality given you can achieve it with the existing tools. We'd be happy to improve the docs and potentially mention whatever you come up with in them!
