### ISSUE TITLE
Custom MessageOptions does not work properly

### ISSUE THREAD

**Issue by yingyingtang-brex** [elixir-protobuf/protobuf#282]
Hey! Is it known that the `MessageOptions` does not work correctly?

I saw in the current tests, both tested related to `MessageOptions` are _**skipped**_:
- [test](https://github.com/tony612/protobuf-elixir/blob/9de6d493813aab52a194abae3c56ea9bf8068314/test/protobuf/protoc/cli_integration_test.exs#L145) "extensions defined and used in the same protoc call"
- [test](https://github.com/tony612/protobuf-elixir/blob/37d2790ca06ea2c11f28ef82d5943761815a2807/test/protobuf/protoc/generator_integration_test.exs#L73) "with messages"

I am a lil confused that if I run the test with `skip` tag, the generated `Test.MessageWithCustomOptions` descriptor has no `__pb_extensions__`, e.g.
```
 options: %Google.Protobuf.MessageOptions{
        __pb_extensions__: %{},
        __unknown_fields__: [{51300, 2, "message_with_custom_options"}],
        deprecated: false,
        map_entry: nil,
        message_set_wire_format: false,
        no_standard_descriptor_accessor: false,
        uninterpreted_option: []
      }
```

Then, if I comment the `skip` tag, and run the test again, the generated descriptor then has the expected `__pb_extensions__`, e.g.
```
options: %Google.Protobuf.MessageOptions{
        __pb_extensions__: %{{Test.PbExtension, :lowercase_name} => "message_with_custom_options"},
        __unknown_fields__: [],
        deprecated: false,
        map_entry: nil,
        message_set_wire_format: false,
        no_standard_descriptor_accessor: false,
        uninterpreted_option: []
      }
```

**Comment by whatyouhide** [comment]
Yes, they are skipped because custom options are not supported yet. We're tracking progress for this on https://github.com/elixir-protobuf/protobuf/issues/138. Thanks for the issue! 💟
