### ISSUE TITLE
Support for unknown field set?

### ISSUE THREAD

**Issue by perezd** [elixir-protobuf/protobuf#285]
Proto3 for a brief period of time decided it was a good idea to drop these and this was promptly reversed to the original behavior: https://developers.google.com/protocol-buffers/docs/proto3#unknowns

I don't believe this library currently supports the expected behavior of "forwarding" unknown fields, is that correct?

Typically, unknown fields are stored in a structure like:
https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/UnknownFieldSet

And when a message with unknown fields is serialized those fields are persisted/forwarded along transparently.

**Comment by whatyouhide** [comment]
@perezd the library has supported this since v0.10. See [the changelog for that version](https://github.com/elixir-protobuf/protobuf/blob/main/CHANGELOG.md#enhancements). 🙃 Thanks for the issue! 💟

**Comment by perezd** [comment]
OK I was confused by this in the readme:

```
Skip unknown fields
```

Also this from the changelog made me wonder if the unknown fields are persisted when the message they are found within is serialized, that wasn't clear from what I've read so far. 

```
Add Protobuf.get_unknown_varints/1, returns fields that could not be decoded.
```

I haven't had a chance to play with the library directly yet! Thanks for the response.
