### ISSUE TITLE
Types have disappeared from generated protobuf file in version 0.10.0

### ISSUE THREAD

**Issue by maxmarcon** [elixir-protobuf/protobuf#297]
Using version 0.9.0 I'm seeing types being generated in my pb.ex file 👍  If I switch to version 0.10.0 the types disappear 😢 

**version 0.9.0**:
```elixir
defmodule Identity.ClassificationType do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto3

  @type t :: integer | :PARTNER | :ASSOCIATE | :C_OTHER | :UNKNOWN | :PARALEGAL | :LEGAL_ASSISTANT

  field :PARTNER, 0
  field :ASSOCIATE, 1
  field :C_OTHER, 2
  field :UNKNOWN, 3
  field :PARALEGAL, 4
  field :LEGAL_ASSISTANT, 5
end
```

**version 0.10.0**:
```elixir
defmodule Identity.ClassificationType do
  @moduledoc false
  use Protobuf, enum: true, protoc_gen_elixir_version: "0.10.0", syntax: :proto3

  field :PARTNER, 0
  field :ASSOCIATE, 1
  field :C_OTHER, 2
  field :UNKNOWN, 3
  field :PARALEGAL, 4
  field :LEGAL_ASSISTANT, 5
end
```

Elixir: 1.13.4
Erlang/OTP: 24
protoc: 3.19.3

How I'm invoking protoc:

`protoc --proto_path=bd-protobuf/identity_service/schema/protobuf --elixir_out=plugins=grpc:./  identity.proto`

**Comment by maxmarcon** [comment]
happy to help with PR if somebody points me in the right direction 😸

**Comment by DaveElGhoul** [comment]
I believe this was intentational, as there are mentions of it in the changelogs:
https://github.com/elixir-protobuf/protobuf/blob/main/CHANGELOG.md

But yea, came across this issue when I was looking for the reason on why structs disappeared from my pb files and my unit tests started raising unknown struct errors

**Comment by maxmarcon** [comment]
The changelog mentions new warnings about types, but it doesn't say that types were removed (also because it wouldn't make any sense)

**Comment by ericmj** [comment]
The types are still there and will be visible in documentation, they have just moved into the `use Protobuf` macro.

**Comment by maxmarcon** [comment]
Thanks. Can you explain what that means? Also at the very least the readme needs to be updated cause it says types will be generated in the pb.ex file

**Comment by ericmj** [comment]
All tooling and documentation can still find and display the types. We have moved their location from the generated code in pb.ex to instead be generated by a macro when the pb.ex file compiles.

A PR that updates the readme would be greatly appreciated.

**Comment by maxmarcon** [comment]
Ok, thanks. I'm back at work now and I'm trying to understand this. I'll be very happy to write the PR :)

See my example at the top of this issue. How do I restore access to those types?

If I now use `Identity.ClassificationType.t()` in the `@spec` for a function, dialyzer will complain that it can't find the type.
I tried to add `use Protobuf` in my module but no luck.

What am I doing wrong? Thanks again.

**Comment by maxmarcon** [comment]
> All tooling and documentation can still find and display the types.

You sure about that?

Version 0.9.0:
```
iex(1)> t MyApp.Identity.ClassificationType
@type t() ::
        integer()
        | :PARTNER
        | :ASSOCIATE
        | :C_OTHER
        | :UNKNOWN
        | :PARALEGAL
        | :LEGAL_ASSISTANT
```

Version 0.10.0:
```
iex(2)> t MyApp.Identity.ClassificationType
No type information for DataIngestion.Identity.ClassificationType was found
```

Looks like the types are simply no longer there.

**Comment by maxmarcon** [comment]
Apologies... My bad. I was using version 0.10.0 of the protoc plugin with version 0.8.0 of the library. When I use version 0.10.0 for both everything works fine 👍  Sorry for the false alarm.

PR for the docs coming soon!
