### ISSUE TITLE
How to encode oneof fields?

### ISSUE THREAD

**Issue by gordoneliel** [elixir-protobuf/protobuf#344]
I've got a protobuf with a oneof field, I need to encode the entire struct with the oneof field. Eg.

`
MyProtoStruct.new(my_oneof: MyOneofField.new()) 
`

I get the follow error:

`(Protobuf.EncodeError) MyProtoStruct#my_oneof should be {key, val}, got: {:ok, <<some-binary-here>>}`

Are there any docs on using oneof fields?

**Comment by whatyouhide** [comment]
You need to use `{:some_name, value}` for oneof fields, not just `value` itself. For example, see [this test](https://github.com/elixir-protobuf/protobuf/blob/9801e93497dc1b980db693765e4782355e63fd9f/test/protobuf/encoder_test.exs#L132).
