### ISSUE TITLE
The plugin one gets with "$ mix escript.install hex protobuf" seems to be old or broken

### ISSUE THREAD

**Issue by asciibeats** [elixir-protobuf/protobuf#345]
It has the same problems that where fixed in #325. See also #321. Using a current ([9801e93](https://github.com/elixir-protobuf/protobuf/commit/9801e93497dc1b980db693765e4782355e63fd9f)) self compiled plugin works as expected.

**Comment by ericmj** [comment]
It will only be updated when a new version is released. If you want to install the development version you can do `mix escript.install github elixir-protobuf/protobuf`.

**Comment by asciibeats** [comment]
That makes sense. I was still on 10 somehow. Thank you!
