### ISSUE TITLE
Consideration in generating options in Messages in OTP 26

### ISSUE THREAD

**Issue by slashmili** [elixir-protobuf/protobuf#361]
Considering that options are [map](https://github.com/elixir-protobuf/protobuf/blob/6c580a2a515c6a1f7a6ec96ecaeed6e0d215dc61/lib/protobuf/protoc/generator/message.ex#L91-L96) and in OTP 26 the order keys of map [is not granted](https://www.erlang.org/blog/otp-26-highlights/#changed-ordering-of-atom-keys), should change it to keyword list?

alternatively [Util.options_to_str](https://github.com/elixir-protobuf/protobuf/blob/main/lib/protobuf/protoc/generator/util.ex#L47) and friends can run sort by key before join map_join?

**Comment by slashmili** [comment]
Just in case it's not clear, this has side effect on the generated file, on every generation we get different file content because the options are generated in a different order.

**Comment by whatyouhide** [comment]
Yes this is a great callout!


> alternatively `Util.options_to_str` and friends can run sort by key before join `map_join`?

Yes this is what we should do 👍

**Comment by whatyouhide** [comment]
cc @savhappy
