### ISSUE TITLE
gen_descriptors and grpc seem to be mutually exclusive

### ISSUE THREAD

**Issue by mergefailure** [elixir-protobuf/protobuf#79]
Hi, forgive my ignorance of GRPC as I'm relatively new to the libraries but I've noticed what is perhaps a bug - `gen_descriptors=true` and `plugins=grpc` seem to be mutually exclusive.

>>$ protoc --elixir_out=gen_descriptors=true:./lib/ *.proto
>>$ protoc --elixir_out=gen_descriptors=true,plugins=grpc:./lib/ *.proto

What I mean is that if I specify `gen_descriptors=true` - the generated modules file doesn't contain any service or stub definitions.

**Comment by tony612** [comment]
What's your protoc-gen-elixir version? I tried this, it works for me. This is my command
```
protoc -I ./protos --elixir_out=gen_descriptors=true,plugins=grpc:lib/
```
I used protoc-gen-elixir from github
```
mix escript.install github tony612/protobuf-elixir
```

**Comment by whatyouhide** [comment]
This seems to be a non-issue here. Closing this, thanks everyone!
