### ISSUE TITLE
Feature Request: Encode to / decode from JSON

### ISSUE THREAD

**Issue by jahell** [elixir-protobuf/protobuf#86]
In proto3 google added an official JSON mapping (https://developers.google.com/protocol-buffers/docs/proto3#json). Is there any plan to support encoding to and decoding from JSON?

**Comment by whatyouhide** [comment]
I would agree to add this feature to this library. I would probably go with a `to_json/1` function and a `from_json/1` function in the generated Protobuf modules, and I would go with a customizable JSON encoder/decoder (so you can choose Jason, Poison, and so on).

**Comment by tony612** [comment]
I think it's a good idea to support this, but there's no plan for the moment.

**Comment by amiel** [comment]
Hi, I'm starting to work on implementing this.

@tony612 how do you feel about depending on https://github.com/michalmuskala/jason/? Any other thoughts you might have for me?

**Comment by whatyouhide** [comment]
Hey @amiel! The company I work at ([Community](https://www.community.com)) is sponsoring some work on this library and @britto already started work on this. :) Feel free to coordinate with him here if you want to!

**Comment by amiel** [comment]
@whatyouhide Awesome!

@britto I have started an implementation in my application (not in a fork of protobuf-elixir) and I'd be happy to share what I have so far.

**Comment by britto** [comment]
Hi @amiel, that's awesome! Yes, I'd love to iterate on it with you.

**Comment by amiel** [comment]
@britto Awesome. Feel free to send me an email at amiel@actionsprout.com.

**Comment by whatyouhide** [comment]
Hey everyone, this has been implemented for a while. It's not in a main release yet but we'll do our best to release a new version soon. Anyways, closing this issue since the feature's on the main branch 😌
