### ISSUE TITLE
Multiple conflicting PbExtension modules

### ISSUE THREAD

**Issue by skwerlman** [elixir-protobuf/protobuf#88]
protobuf-elixir: 0.8.0-beta.1
elixir: 1.10.1
otp: 22.2.7

I am trying to compile [these .proto files](https://github.com/Cockatrice/Cockatrice/tree/master/common/pb) using version 0.8.0-beta.1, and in most of the resulting 155 elixir files I get a PbExtension module. Elixir can obviously only handle one module with a given name, so this fails to compile.

**Comment by tony612** [comment]
This is because there's no package for different extend. Let me try to fix it. Thanks for reporting.

**Comment by britto** [comment]
This causes some "module redefined" warnings on the newly introduced benchmark datasets (#117) too. Something to keep in mind if we eventually decide to add them to CI.

**Comment by whatyouhide** [comment]
@britto @ericmj do we still have this issue?

**Comment by britto** [comment]
@whatyouhide Yes, we do. I think we'd have to introduce some randomness into the generated extension module name to prevent that.

**Comment by whatyouhide** [comment]
Can we get a small reproducing case? Is this a specific issue to `import`/`extend` in proto2 or does it apply to proto3 as well?

**Comment by britto** [comment]
It happens when we define extensions for the same module in separate files. Here's a small reproducingn case. Consider the following 3 proto files:

```protobuf
// base.proto
syntax = "proto2";

package bugs;

message Base {
  optional string name = 1;
  extensions 100 to max;
}
```

```protobuf
// ext1.proto
syntax = "proto2";

import "bug.proto";

package bugs;

message Ext1 {
  extend Base {
    optional string first_name = 101;
  }
}
```

```protobuf
// ext2.proto
syntax = "proto2";

import "bug.proto";

package bugs;

message Ext2 {
  extend Base {
    optional string last_name = 102;
  }
}
```

When we compile them, we'll end up with 3 `.pb.ex` files. The extension files will both define their own module and a conflicting extension module as well:

```elixir
# ext1.pb.ex
defmodule Bugs.Ext1 do
  @moduledoc false
  use Protobuf, syntax: :proto2
  @type t :: %__MODULE__{}

  defstruct []

  def transform_module(), do: nil
end

defmodule Bugs.PbExtension do
  @moduledoc false
  use Protobuf, syntax: :proto2
  extend Bugs.Base, :"Ext1.first_name", 101, optional: true, type: :string
end
```

```elixir
# ext2.pb.ex
defmodule Bugs.Ext2 do
  @moduledoc false
  use Protobuf, syntax: :proto2
  @type t :: %__MODULE__{}

  defstruct []

  def transform_module(), do: nil
end

defmodule Bugs.PbExtension do
  @moduledoc false
  use Protobuf, syntax: :proto2
  extend Bugs.Base, :"Ext2.last_name", 102, optional: true, type: :string
end
```

Then we'll get a compilation warning saying `redefining module Bugs.PbExtension (current version loaded from _build/...)`.

**Comment by ericmj** [comment]
Is it possible to namespace the extension module under the name of the module it is extending? So that the module name would be `Bugs.Ext1.PbExtension`.

**Comment by britto** [comment]
@ericmj I think so, but we'd still be unable to fix the problem for unscoped extensions. Similar example as above, but without defining extension modules:

```protobuf
// base.proto
syntax = "proto2";

package bugs;

message Base {
  optional string name = 1;
  extensions 100 to max;
}
```

```protobuf
// ext1.proto
syntax = "proto2";

import "base.proto";

package bugs;

extend Base {
  optional string first_name = 101;
}
```

```protobuf
// ext2.proto
syntax = "proto2";

import "base.proto";

package bugs;

extend Base {
  optional string last_name = 102;
}
```

We'll also end up with 3 `.pb.ex` files and the extension modules will have conflicting names too:

```elixir
# ext1.pb.ex
defmodule Bugs.PbExtension do
  @moduledoc false
  use Protobuf, syntax: :proto2
  extend Bugs.Base, :first_name, 101, optional: true, type: :string
end
```

```elixir
# ext2.pb.ex
defmodule Bugs.PbExtension do
  @moduledoc false
  use Protobuf, syntax: :proto2
  extend Bugs.Base, :last_name, 102, optional: true, type: :string
end
```
